server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      api-key: demo
      model-name: gpt-4o-mini
      log-requests: true  #应用程序发送给大模型的请求日志
      log-responses: true   #应用程序发送给大模型的响应日志
      base-url: http://langchain4j.dev/demo/openai/v1
#系统日至级别
logging:
  level:
    root: debug
