server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      api-key: ${DASH_SCOPE_API_KEY}
      model-name: deepseek-v3
      log-requests: true  #应用程序发送给大模型的请求日志
      log-responses: true   #应用程序发送给大模型的响应日志
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      temperature: 0.9

  #ollama
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:1.5b
      log-requests: true
      log-responses: true
      temperature: 0.8
      timeout: PT60S

  community:
    dashscope:
      chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: qwen-max




#系统日至级别
logging:
  level:
    root: debug
